#!/usr/bin/env bash
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: ./create-secret <name> <secret>"
  exit 1
fi
set -e
pushd /etc/nixos >> /dev/null
printf '%s' "$2" | RULES=secrets/secrets.nix nix run .#agenix -- -e secrets/$1.age
popd >> /dev/null
